#!/bin/bash

#
# Terminate on error
#
set -o errexit

#
# Check location
#
if [[ ! -f "../shamirs-secret-sharing/alt-build/download-compiler-deps.sh" ]]
then
  echo "ERROR -> 'make' must be called from the (sub-)project directory."
  exit
fi

#
# evaluate parameter
#
readonly SCALA_VERSION_REGEX="^--scala-version=[0-9]{1,2}\\.[0-9]{1,2}\\.[0-9]{1,2}$"
readonly SHAMIR_VERSION_REGEX="^--shamir-version=[0-9]{1,2}\\.[0-9]{1,2}\\.[0-9]{1,2}$"
ARGS=$*
for ARG in ${ARGS}
do
  echo ARG=${ARG}
  if [[ "${ARG}" == "all" ]]
  then
    readonly MAKE_ALL=ON
  fi
  if [[ "${ARG}" == "clean" ]]
  then
    readonly CLEAN_UP=ON
  fi
  if [[ "${ARG}" =~ ${SCALA_VERSION_REGEX} ]]
  then
    readonly SCALA_VERSION=${ARG:16}
    export SCALA_VERSION
  fi
  if [[ "${ARG}" =~ ${SHAMIR_VERSION_REGEX} ]]
  then
    readonly SHAMIR_VERSION=${ARG:17}
    export SHAMIR_VERSION
  fi
done
echo MAKE_ALL=${MAKE_ALL}
echo CLEAN_UP=${CLEAN_UP}
if [[ -z "${SCALA_VERSION}" ]]
then
  SCALA_VERSION=3.8.3
fi
echo SCALA_VERSION=${SCALA_VERSION}
if [[ -z "${SHAMIR_VERSION}" ]]
then
  SHAMIR_VERSION=1.4.0
fi
echo SHAMIR_VERSION=${SHAMIR_VERSION}
echo

#
# Clean up
#
if [[ "${CLEAN_UP}" == "ON" ]]
then
  ./alt-build/cleanup.sh
fi

#
# Download the Scala 3 compiler dependencies (if required), compile the main sources and build a jar-archive. Thereupon compile the test sources
# and run the tests. Finally, download the Scaladoc 3 dependencies (if required), generate the scaladocs and build a jar-archive accordingly.
#
if [[ ${MAKE_ALL} == "ON" ]]
then
  ./alt-build/download-compiler-deps.sh
  ./alt-build/compile.sh
  ./alt-build/test-compile.sh
  ./alt-build/run-tests.sh
  ./alt-build/download-scaladoc-deps.sh
  ./alt-build/generate-scaladoc.sh
fi

